/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BondingCurvePrimaryMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "basePrice_sats_per_token"
      | "buy"
      | "calculatePurchaseReturn"
      | "calculateSaleReturn"
      | "creator"
      | "creatorFeeRate"
      | "factory"
      | "getCurrentPrice"
      | "priceIncrement_sats_per_token_per_token"
      | "sell"
      | "token"
      | "totalBTCDepositedSats"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "TokensPurchased" | "TokensSold"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "basePrice_sats_per_token",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePurchaseReturn",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateSaleReturn",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "creator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "creatorFeeRate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceIncrement_sats_per_token_per_token",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalBTCDepositedSats",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "basePrice_sats_per_token",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculatePurchaseReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateSaleReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "creator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creatorFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceIncrement_sats_per_token_per_token",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalBTCDepositedSats",
    data: BytesLike
  ): Result;
}

export namespace TokensPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    intentId: BytesLike,
    btcAmountSats: BigNumberish,
    tokenAmountBaseUnits: BigNumberish,
    newTotalSupply: BigNumberish,
    newPrice: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    intentId: string,
    btcAmountSats: bigint,
    tokenAmountBaseUnits: bigint,
    newTotalSupply: bigint,
    newPrice: bigint
  ];
  export interface OutputObject {
    buyer: string;
    intentId: string;
    btcAmountSats: bigint;
    tokenAmountBaseUnits: bigint;
    newTotalSupply: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensSoldEvent {
  export type InputTuple = [
    seller: AddressLike,
    intentId: BytesLike,
    btcAmountSats: BigNumberish,
    tokenAmountBaseUnits: BigNumberish,
    newTotalSupply: BigNumberish,
    newPrice: BigNumberish
  ];
  export type OutputTuple = [
    seller: string,
    intentId: string,
    btcAmountSats: bigint,
    tokenAmountBaseUnits: bigint,
    newTotalSupply: bigint,
    newPrice: bigint
  ];
  export interface OutputObject {
    seller: string;
    intentId: string;
    btcAmountSats: bigint;
    tokenAmountBaseUnits: bigint;
    newTotalSupply: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BondingCurvePrimaryMarket extends BaseContract {
  connect(runner?: ContractRunner | null): BondingCurvePrimaryMarket;
  waitForDeployment(): Promise<this>;

  interface: BondingCurvePrimaryMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  basePrice_sats_per_token: TypedContractMethod<[], [bigint], "view">;

  buy: TypedContractMethod<
    [intentId: BytesLike, minTokensOut: BigNumberish],
    [void],
    "payable"
  >;

  calculatePurchaseReturn: TypedContractMethod<
    [btcInSats: BigNumberish, currentSupplyBaseUnits: BigNumberish],
    [bigint],
    "view"
  >;

  calculateSaleReturn: TypedContractMethod<
    [tokenAmountBaseUnits: BigNumberish, currentSupplyBaseUnits: BigNumberish],
    [bigint],
    "view"
  >;

  creator: TypedContractMethod<[], [string], "view">;

  creatorFeeRate: TypedContractMethod<[], [bigint], "view">;

  factory: TypedContractMethod<[], [string], "view">;

  getCurrentPrice: TypedContractMethod<[], [bigint], "view">;

  priceIncrement_sats_per_token_per_token: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  sell: TypedContractMethod<
    [
      intentId: BytesLike,
      tokenAmountBaseUnits: BigNumberish,
      minBtcOut: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  totalBTCDepositedSats: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "basePrice_sats_per_token"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [intentId: BytesLike, minTokensOut: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "calculatePurchaseReturn"
  ): TypedContractMethod<
    [btcInSats: BigNumberish, currentSupplyBaseUnits: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateSaleReturn"
  ): TypedContractMethod<
    [tokenAmountBaseUnits: BigNumberish, currentSupplyBaseUnits: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "creator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "creatorFeeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCurrentPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "priceIncrement_sats_per_token_per_token"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<
    [
      intentId: BytesLike,
      tokenAmountBaseUnits: BigNumberish,
      minBtcOut: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalBTCDepositedSats"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "TokensPurchased"
  ): TypedContractEvent<
    TokensPurchasedEvent.InputTuple,
    TokensPurchasedEvent.OutputTuple,
    TokensPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "TokensSold"
  ): TypedContractEvent<
    TokensSoldEvent.InputTuple,
    TokensSoldEvent.OutputTuple,
    TokensSoldEvent.OutputObject
  >;

  filters: {
    "TokensPurchased(address,bytes32,uint256,uint256,uint256,uint256)": TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;
    TokensPurchased: TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;

    "TokensSold(address,bytes32,uint256,uint256,uint256,uint256)": TypedContractEvent<
      TokensSoldEvent.InputTuple,
      TokensSoldEvent.OutputTuple,
      TokensSoldEvent.OutputObject
    >;
    TokensSold: TypedContractEvent<
      TokensSoldEvent.InputTuple,
      TokensSoldEvent.OutputTuple,
      TokensSoldEvent.OutputObject
    >;
  };
}
