/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace LaunchFactory {
  export type LaunchMetadataStruct = {
    tokenAddress: AddressLike;
    curveAddress: AddressLike;
    creator: AddressLike;
    timestamp: BigNumberish;
    mode: BigNumberish;
  };

  export type LaunchMetadataStructOutput = [
    tokenAddress: string,
    curveAddress: string,
    creator: string,
    timestamp: bigint,
    mode: bigint
  ] & {
    tokenAddress: string;
    curveAddress: string;
    creator: string;
    timestamp: bigint;
    mode: bigint;
  };
}

export interface LaunchFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_BASE_PRICE"
      | "MAX_CREATOR_FEE_RATE"
      | "MAX_PRICE_INCREMENT"
      | "MAX_SUPPLY_CAP"
      | "MIN_BASE_PRICE"
      | "MIN_PRICE_INCREMENT"
      | "MIN_SUPPLY_CAP"
      | "admin"
      | "allLaunches"
      | "createLaunch"
      | "feeRecipient"
      | "getLaunch"
      | "launchCount"
      | "launches"
      | "paused"
      | "protocolFeeRate"
      | "setFeeRecipient"
      | "setPaused"
      | "setProtocolFeeRate"
      | "transferAdmin"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeRecipientUpdated"
      | "LaunchCreated"
      | "PauseStatusUpdated"
      | "ProtocolFeeRateUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_BASE_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_CREATOR_FEE_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PRICE_INCREMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SUPPLY_CAP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_BASE_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_PRICE_INCREMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_SUPPLY_CAP",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allLaunches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createLaunch",
    values: [
      BytesLike,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLaunch",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "launchCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "launches",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolFeeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "setProtocolFeeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_BASE_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_CREATOR_FEE_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PRICE_INCREMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SUPPLY_CAP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_BASE_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_PRICE_INCREMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_SUPPLY_CAP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allLaunches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createLaunch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLaunch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "launchCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "launches", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
}

export namespace FeeRecipientUpdatedEvent {
  export type InputTuple = [
    oldRecipient: AddressLike,
    newRecipient: AddressLike
  ];
  export type OutputTuple = [oldRecipient: string, newRecipient: string];
  export interface OutputObject {
    oldRecipient: string;
    newRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LaunchCreatedEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    curveAddress: AddressLike,
    creator: AddressLike,
    intentId: BytesLike,
    supplyCap: BigNumberish,
    basePrice: BigNumberish,
    priceIncrement: BigNumberish,
    mode: BigNumberish,
    modeMetadata: BytesLike
  ];
  export type OutputTuple = [
    tokenAddress: string,
    curveAddress: string,
    creator: string,
    intentId: string,
    supplyCap: bigint,
    basePrice: bigint,
    priceIncrement: bigint,
    mode: bigint,
    modeMetadata: string
  ];
  export interface OutputObject {
    tokenAddress: string;
    curveAddress: string;
    creator: string;
    intentId: string;
    supplyCap: bigint;
    basePrice: bigint;
    priceIncrement: bigint;
    mode: bigint;
    modeMetadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauseStatusUpdatedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolFeeRateUpdatedEvent {
  export type InputTuple = [oldRate: BigNumberish, newRate: BigNumberish];
  export type OutputTuple = [oldRate: bigint, newRate: bigint];
  export interface OutputObject {
    oldRate: bigint;
    newRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LaunchFactory extends BaseContract {
  connect(runner?: ContractRunner | null): LaunchFactory;
  waitForDeployment(): Promise<this>;

  interface: LaunchFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_BASE_PRICE: TypedContractMethod<[], [bigint], "view">;

  MAX_CREATOR_FEE_RATE: TypedContractMethod<[], [bigint], "view">;

  MAX_PRICE_INCREMENT: TypedContractMethod<[], [bigint], "view">;

  MAX_SUPPLY_CAP: TypedContractMethod<[], [bigint], "view">;

  MIN_BASE_PRICE: TypedContractMethod<[], [bigint], "view">;

  MIN_PRICE_INCREMENT: TypedContractMethod<[], [bigint], "view">;

  MIN_SUPPLY_CAP: TypedContractMethod<[], [bigint], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  allLaunches: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  createLaunch: TypedContractMethod<
    [
      intentId: BytesLike,
      name: string,
      symbol: string,
      supplyCap: BigNumberish,
      basePrice: BigNumberish,
      priceIncrement: BigNumberish,
      creatorFeeRate: BigNumberish,
      mode: BigNumberish,
      modeMetadata: BytesLike
    ],
    [[string, string] & { tokenAddress: string; curveAddress: string }],
    "nonpayable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getLaunch: TypedContractMethod<
    [tokenAddress: AddressLike],
    [LaunchFactory.LaunchMetadataStructOutput],
    "view"
  >;

  launchCount: TypedContractMethod<[], [bigint], "view">;

  launches: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, bigint] & {
        tokenAddress: string;
        curveAddress: string;
        creator: string;
        timestamp: bigint;
        mode: bigint;
      }
    ],
    "view"
  >;

  paused: TypedContractMethod<[], [boolean], "view">;

  protocolFeeRate: TypedContractMethod<[], [bigint], "view">;

  setFeeRecipient: TypedContractMethod<
    [newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[_paused: boolean], [void], "nonpayable">;

  setProtocolFeeRate: TypedContractMethod<
    [newRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_BASE_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_CREATOR_FEE_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PRICE_INCREMENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SUPPLY_CAP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_BASE_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_PRICE_INCREMENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_SUPPLY_CAP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allLaunches"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createLaunch"
  ): TypedContractMethod<
    [
      intentId: BytesLike,
      name: string,
      symbol: string,
      supplyCap: BigNumberish,
      basePrice: BigNumberish,
      priceIncrement: BigNumberish,
      creatorFeeRate: BigNumberish,
      mode: BigNumberish,
      modeMetadata: BytesLike
    ],
    [[string, string] & { tokenAddress: string; curveAddress: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLaunch"
  ): TypedContractMethod<
    [tokenAddress: AddressLike],
    [LaunchFactory.LaunchMetadataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "launchCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "launches"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, bigint] & {
        tokenAddress: string;
        curveAddress: string;
        creator: string;
        timestamp: bigint;
        mode: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolFeeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[newRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[_paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProtocolFeeRate"
  ): TypedContractMethod<[newRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FeeRecipientUpdated"
  ): TypedContractEvent<
    FeeRecipientUpdatedEvent.InputTuple,
    FeeRecipientUpdatedEvent.OutputTuple,
    FeeRecipientUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LaunchCreated"
  ): TypedContractEvent<
    LaunchCreatedEvent.InputTuple,
    LaunchCreatedEvent.OutputTuple,
    LaunchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PauseStatusUpdated"
  ): TypedContractEvent<
    PauseStatusUpdatedEvent.InputTuple,
    PauseStatusUpdatedEvent.OutputTuple,
    PauseStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolFeeRateUpdated"
  ): TypedContractEvent<
    ProtocolFeeRateUpdatedEvent.InputTuple,
    ProtocolFeeRateUpdatedEvent.OutputTuple,
    ProtocolFeeRateUpdatedEvent.OutputObject
  >;

  filters: {
    "FeeRecipientUpdated(address,address)": TypedContractEvent<
      FeeRecipientUpdatedEvent.InputTuple,
      FeeRecipientUpdatedEvent.OutputTuple,
      FeeRecipientUpdatedEvent.OutputObject
    >;
    FeeRecipientUpdated: TypedContractEvent<
      FeeRecipientUpdatedEvent.InputTuple,
      FeeRecipientUpdatedEvent.OutputTuple,
      FeeRecipientUpdatedEvent.OutputObject
    >;

    "LaunchCreated(address,address,address,bytes32,uint256,uint256,uint256,uint8,bytes32)": TypedContractEvent<
      LaunchCreatedEvent.InputTuple,
      LaunchCreatedEvent.OutputTuple,
      LaunchCreatedEvent.OutputObject
    >;
    LaunchCreated: TypedContractEvent<
      LaunchCreatedEvent.InputTuple,
      LaunchCreatedEvent.OutputTuple,
      LaunchCreatedEvent.OutputObject
    >;

    "PauseStatusUpdated(bool)": TypedContractEvent<
      PauseStatusUpdatedEvent.InputTuple,
      PauseStatusUpdatedEvent.OutputTuple,
      PauseStatusUpdatedEvent.OutputObject
    >;
    PauseStatusUpdated: TypedContractEvent<
      PauseStatusUpdatedEvent.InputTuple,
      PauseStatusUpdatedEvent.OutputTuple,
      PauseStatusUpdatedEvent.OutputObject
    >;

    "ProtocolFeeRateUpdated(uint256,uint256)": TypedContractEvent<
      ProtocolFeeRateUpdatedEvent.InputTuple,
      ProtocolFeeRateUpdatedEvent.OutputTuple,
      ProtocolFeeRateUpdatedEvent.OutputObject
    >;
    ProtocolFeeRateUpdated: TypedContractEvent<
      ProtocolFeeRateUpdatedEvent.InputTuple,
      ProtocolFeeRateUpdatedEvent.OutputTuple,
      ProtocolFeeRateUpdatedEvent.OutputObject
    >;
  };
}
