/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface NftFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "allCollections"
      | "createCollection"
      | "getAllCollections"
      | "isCollection"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CollectionCreated"): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allCollections",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCollection",
    values: [
      BytesLike,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllCollections",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isCollection",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allCollections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllCollections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCollection",
    data: BytesLike
  ): Result;
}

export namespace CollectionCreatedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    creator: AddressLike,
    collection: AddressLike,
    name: string,
    symbol: string,
    maxSupply: BigNumberish,
    mintPrice: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    creator: string,
    collection: string,
    name: string,
    symbol: string,
    maxSupply: bigint,
    mintPrice: bigint
  ];
  export interface OutputObject {
    intentId: string;
    creator: string;
    collection: string;
    name: string;
    symbol: string;
    maxSupply: bigint;
    mintPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NftFactory extends BaseContract {
  connect(runner?: ContractRunner | null): NftFactory;
  waitForDeployment(): Promise<this>;

  interface: NftFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  allCollections: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  createCollection: TypedContractMethod<
    [
      intentId: BytesLike,
      name: string,
      symbol: string,
      maxSupply: BigNumberish,
      mintPrice: BigNumberish,
      maxPerWallet: BigNumberish,
      metadataCID: string
    ],
    [string],
    "nonpayable"
  >;

  getAllCollections: TypedContractMethod<[], [string[]], "view">;

  isCollection: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allCollections"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createCollection"
  ): TypedContractMethod<
    [
      intentId: BytesLike,
      name: string,
      symbol: string,
      maxSupply: BigNumberish,
      mintPrice: BigNumberish,
      maxPerWallet: BigNumberish,
      metadataCID: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllCollections"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isCollection"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "CollectionCreated"
  ): TypedContractEvent<
    CollectionCreatedEvent.InputTuple,
    CollectionCreatedEvent.OutputTuple,
    CollectionCreatedEvent.OutputObject
  >;

  filters: {
    "CollectionCreated(bytes32,address,address,string,string,uint256,uint256)": TypedContractEvent<
      CollectionCreatedEvent.InputTuple,
      CollectionCreatedEvent.OutputTuple,
      CollectionCreatedEvent.OutputObject
    >;
    CollectionCreated: TypedContractEvent<
      CollectionCreatedEvent.InputTuple,
      CollectionCreatedEvent.OutputTuple,
      CollectionCreatedEvent.OutputObject
    >;
  };
}
