/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace NftMarketplace {
  export type ListingStruct = {
    seller: AddressLike;
    priceSats: BigNumberish;
    active: boolean;
  };

  export type ListingStructOutput = [
    seller: string,
    priceSats: bigint,
    active: boolean
  ] & { seller: string; priceSats: bigint; active: boolean };
}

export interface NftMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature: "buy" | "delist" | "getListing" | "list" | "listings"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "NFTDelisted" | "NFTListed" | "NFTSold"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buy",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "delist",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getListing",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "list",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listings",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "delist", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getListing", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "list", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
}

export namespace NFTDelistedEvent {
  export type InputTuple = [
    collection: AddressLike,
    tokenId: BigNumberish,
    seller: AddressLike
  ];
  export type OutputTuple = [
    collection: string,
    tokenId: bigint,
    seller: string
  ];
  export interface OutputObject {
    collection: string;
    tokenId: bigint;
    seller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTListedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    collection: AddressLike,
    tokenId: BigNumberish,
    seller: AddressLike,
    priceSats: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    collection: string,
    tokenId: bigint,
    seller: string,
    priceSats: bigint
  ];
  export interface OutputObject {
    intentId: string;
    collection: string;
    tokenId: bigint;
    seller: string;
    priceSats: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTSoldEvent {
  export type InputTuple = [
    intentId: BytesLike,
    collection: AddressLike,
    tokenId: BigNumberish,
    seller: AddressLike,
    buyer: AddressLike,
    priceSats: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    collection: string,
    tokenId: bigint,
    seller: string,
    buyer: string,
    priceSats: bigint
  ];
  export interface OutputObject {
    intentId: string;
    collection: string;
    tokenId: bigint;
    seller: string;
    buyer: string;
    priceSats: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NftMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): NftMarketplace;
  waitForDeployment(): Promise<this>;

  interface: NftMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buy: TypedContractMethod<
    [intentId: BytesLike, collection: AddressLike, tokenId: BigNumberish],
    [void],
    "payable"
  >;

  delist: TypedContractMethod<
    [collection: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getListing: TypedContractMethod<
    [collection: AddressLike, tokenId: BigNumberish],
    [NftMarketplace.ListingStructOutput],
    "view"
  >;

  list: TypedContractMethod<
    [
      intentId: BytesLike,
      collection: AddressLike,
      tokenId: BigNumberish,
      priceSats: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  listings: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, boolean] & {
        seller: string;
        priceSats: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [intentId: BytesLike, collection: AddressLike, tokenId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "delist"
  ): TypedContractMethod<
    [collection: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getListing"
  ): TypedContractMethod<
    [collection: AddressLike, tokenId: BigNumberish],
    [NftMarketplace.ListingStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "list"
  ): TypedContractMethod<
    [
      intentId: BytesLike,
      collection: AddressLike,
      tokenId: BigNumberish,
      priceSats: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, boolean] & {
        seller: string;
        priceSats: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "NFTDelisted"
  ): TypedContractEvent<
    NFTDelistedEvent.InputTuple,
    NFTDelistedEvent.OutputTuple,
    NFTDelistedEvent.OutputObject
  >;
  getEvent(
    key: "NFTListed"
  ): TypedContractEvent<
    NFTListedEvent.InputTuple,
    NFTListedEvent.OutputTuple,
    NFTListedEvent.OutputObject
  >;
  getEvent(
    key: "NFTSold"
  ): TypedContractEvent<
    NFTSoldEvent.InputTuple,
    NFTSoldEvent.OutputTuple,
    NFTSoldEvent.OutputObject
  >;

  filters: {
    "NFTDelisted(address,uint256,address)": TypedContractEvent<
      NFTDelistedEvent.InputTuple,
      NFTDelistedEvent.OutputTuple,
      NFTDelistedEvent.OutputObject
    >;
    NFTDelisted: TypedContractEvent<
      NFTDelistedEvent.InputTuple,
      NFTDelistedEvent.OutputTuple,
      NFTDelistedEvent.OutputObject
    >;

    "NFTListed(bytes32,address,uint256,address,uint256)": TypedContractEvent<
      NFTListedEvent.InputTuple,
      NFTListedEvent.OutputTuple,
      NFTListedEvent.OutputObject
    >;
    NFTListed: TypedContractEvent<
      NFTListedEvent.InputTuple,
      NFTListedEvent.OutputTuple,
      NFTListedEvent.OutputObject
    >;

    "NFTSold(bytes32,address,uint256,address,address,uint256)": TypedContractEvent<
      NFTSoldEvent.InputTuple,
      NFTSoldEvent.OutputTuple,
      NFTSoldEvent.OutputObject
    >;
    NFTSold: TypedContractEvent<
      NFTSoldEvent.InputTuple,
      NFTSoldEvent.OutputTuple,
      NFTSoldEvent.OutputObject
    >;
  };
}
